// import type { PrinterState } from '../types/printer'
// import { ThermalBadge } from './ThermalBadge'

// interface Props {
//   state: PrinterState
// }

// export function OutputPanel({ state }: Props) {
//   const { material, nozzleTemp, bedTemp, bed } = state
//   const volume = ((bed.width * bed.depth * bed.height) / 1000).toFixed(1)

//   return (
//     <div className="flex flex-col gap-4 p-4 bg-slate-900 rounded-xl border border-slate-700">
//       <h2 className="text-sm font-semibold text-slate-300">Summary</h2>

//       <ThermalBadge
//         label="Nozzle"
//         value={nozzleTemp}
//         min={material.nozzleTemp.min}
//         max={material.nozzleTemp.max}
//       />
//       <ThermalBadge
//         label="Bed"
//         value={bedTemp}
//         min={material.bedTemp.min}
//         max={material.bedTemp.max}
//       />

//       <div className="flex items-center justify-between px-3 py-2 rounded-lg bg-slate-800 border border-slate-600">
//         <span className="text-sm text-slate-300">Material</span>
//         <span className="text-sm font-semibold" style={{ color: material.color }}>
//           {material.name}
//         </span>
//       </div>

//       <div className="flex items-center justify-between px-3 py-2 rounded-lg bg-slate-800 border border-slate-600">
//         <span className="text-sm text-slate-300">Build Volume</span>
//         <span className="text-sm font-semibold text-slate-100">{volume} cm³</span>
//       </div>

//       <div className="flex items-center justify-between px-3 py-2 rounded-lg bg-slate-800 border border-slate-600">
//         <span className="text-sm text-slate-300">Bed Size</span>
//         <span className="text-sm font-semibold text-slate-100">
//           {bed.width} × {bed.depth} × {bed.height} mm
//         </span>
//       </div>
//     </div>
//   )
// }
import React, { useState } from 'react';
import type { PrinterState } from '../types/printer';


interface Props {
  state: PrinterState;
}

export const OutputPanel: React.FC<Props> = ({ state }) => {
  const [activeTab, setActiveTab] = useState<'json' | 'gcode'>('json');
  const [copied, setCopied] = useState(false);

  const jsonOutput = JSON.stringify(state, null, 2);

  const gcodeOutput = `; 3D Printer Start G-code
; Generated by 3D Printer Visualizer
; Material: ${state.material}
; Bed Size: ${state.bedWidth}x${state.bedDepth}mm

M140 S${state.bedTemp}  ; Set bed temp
M104 S${state.nozzleTemp}  ; Set nozzle temp
M190 S${state.bedTemp}  ; Wait for bed temp
M109 S${state.nozzleTemp}  ; Wait for nozzle temp
G28  ; Home all axes
G29  ; Auto bed leveling (if available)
G92 E0  ; Reset extruder position
G1 Z2.0 F3000  ; Move Z up
; Ready to print...`;

  const copyToClipboard = () => {
    const text = activeTab === 'json' ? jsonOutput : gcodeOutput;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-dark-900/90 backdrop-blur-md rounded-2xl p-6 sm:p-7 border border-slate-800/80 shadow-panel space-y-4">
      <div className="flex items-center justify-between border-b border-slate-800/80 pb-4">
        <div className="flex items-center space-x-3">
          <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400 text-sm font-mono">
            {activeTab === 'json' ? '{ }' : 'G>'}
          </div>
          <div>
            <h2 className="text-lg font-semibold text-slate-100 tracking-tight">Code Export</h2>
            <p className="text-xs text-slate-400">JSON specification & printer start script</p>
          </div>
        </div>

        <button
          type="button"
          onClick={copyToClipboard}
          className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all duration-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-900 ${
            copied
              ? 'bg-emerald-600 text-white shadow-glow-sm shadow-emerald-500/30'
              : 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white shadow-glow-sm shadow-blue-500/20 active:scale-95'
          }`}
        >
          <span>{copied ? '✓ Copied!' : '📋 Copy Code'}</span>
        </button>
      </div>

      {/* Tabs */}
      <div className="flex p-1 rounded-xl bg-dark-950/70 border border-slate-800/70 gap-1">
        <button
          type="button"
          onClick={() => setActiveTab('json')}
          className={`flex-1 py-1.5 px-3 rounded-lg text-xs font-medium transition-all duration-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 ${
            activeTab === 'json'
              ? 'bg-dark-800 text-white shadow-sm border border-slate-700/60 font-semibold'
              : 'text-slate-400 hover:text-slate-200 hover:bg-dark-850/40'
          }`}
        >
          JSON Config
        </button>
        <button
          type="button"
          onClick={() => setActiveTab('gcode')}
          className={`flex-1 py-1.5 px-3 rounded-lg text-xs font-medium transition-all duration-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 ${
            activeTab === 'gcode'
              ? 'bg-dark-800 text-white shadow-sm border border-slate-700/60 font-semibold'
              : 'text-slate-400 hover:text-slate-200 hover:bg-dark-850/40'
          }`}
        >
          G-Code Snippet
        </button>
      </div>

      {/* Code Block */}
      <div className="relative rounded-xl overflow-hidden border border-slate-800 bg-dark-950/90 shadow-inner">
        <div className="flex items-center justify-between px-3 py-1.5 bg-dark-950 border-b border-slate-800 text-[11px] font-mono text-slate-500">
          <span>{activeTab === 'json' ? 'config.json' : 'start_sequence.gcode'}</span>
          <span>UTF-8</span>
        </div>
        <pre className="p-4 text-xs font-mono text-cyan-300/90 overflow-x-auto max-h-56 overflow-y-auto leading-relaxed">
          <code>{activeTab === 'json' ? jsonOutput : gcodeOutput}</code>
        </pre>
      </div>
    </div>
  );
};